/*
 * mundicoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/02/2017
 */

package models_pkg

import "time"

/*
 * Structure for the custom type CreateSubscriptionRequest
 */
type CreateSubscriptionRequest struct {
    PlanId                 string          `json:"plan_id" form:"plan_id"` //TODO: Write general description for this field
    Customer               CreateCustomerRequest `json:"customer" form:"customer"` //TODO: Write general description for this field
    CreditCard             CreateCreditCardRequest `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
    Code                   string          `json:"code" form:"code"` //TODO: Write general description for this field
    CustomerId             string          `json:"customer_id" form:"customer_id"` //TODO: Write general description for this field
    CreditCardId           string          `json:"credit_card_id" form:"credit_card_id"` //TODO: Write general description for this field
    CreditCardGatewayId    string          `json:"credit_card_gateway_id" form:"credit_card_gateway_id"` //TODO: Write general description for this field
    PaymentMethod          string          `json:"payment_method" form:"payment_method"` //TODO: Write general description for this field
    BillingType            string          `json:"billing_type" form:"billing_type"` //TODO: Write general description for this field
    StatementDescriptor    string          `json:"statement_descriptor" form:"statement_descriptor"` //TODO: Write general description for this field
    Description            string          `json:"description" form:"description"` //TODO: Write general description for this field
    Currency               string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Interval               string          `json:"interval" form:"interval"` //TODO: Write general description for this field
    IntervalCount          int64           `json:"interval_count" form:"interval_count"` //TODO: Write general description for this field
    PricingScheme          CreatePricingSchemeRequest `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    Items                  []*CreateSubscriptionItemRequest `json:"items" form:"items"` //TODO: Write general description for this field
    Shipping               CreateShippingRequest `json:"shipping" form:"shipping"` //TODO: Write general description for this field
    Discounts              []*CreateDiscountRequest `json:"discounts" form:"discounts"` //TODO: Write general description for this field
    Metadata               map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    BillingDay             *int64          `json:"billing_day,omitempty" form:"billing_day,omitempty"` //TODO: Write general description for this field
    Installments           *int64          `json:"installments,omitempty" form:"installments,omitempty"` //TODO: Write general description for this field
    StartAt                *time.Time      `json:"start_at,omitempty" form:"start_at,omitempty"` //TODO: Write general description for this field
    MinimumPrice           *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
    Cycles                 *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetBoletoTransactionResponse
 */
type GetBoletoTransactionResponse struct {
    GetTransactionResponse // Anonymous member to emulate model inheritence
    Url             string          `json:"url" form:"url"` //TODO: Write general description for this field
    BarCode         string          `json:"bar_code" form:"bar_code"` //TODO: Write general description for this field
    NossoNumero     string          `json:"nosso_numero" form:"nosso_numero"` //TODO: Write general description for this field
    Bank            string          `json:"bank" form:"bank"` //TODO: Write general description for this field
    DocumentNumber  string          `json:"document_number" form:"document_number"` //TODO: Write general description for this field
    Instructions    string          `json:"instructions" form:"instructions"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetCreditCardTransactionResponse
 */
type GetCreditCardTransactionResponse struct {
    GetTransactionResponse    // Anonymous member to emulate model inheritence
    StatementDescriptor       string          `json:"statement_descriptor" form:"statement_descriptor"` //TODO: Write general description for this field
    Acquirer                  string          `json:"acquirer" form:"acquirer"` //TODO: Write general description for this field
    AcquirerAffiliationCode   string          `json:"acquirer_affiliation_code" form:"acquirer_affiliation_code"` //TODO: Write general description for this field
    AcquirerTid               string          `json:"acquirer_tid" form:"acquirer_tid"` //TODO: Write general description for this field
    AcquirerNsu               string          `json:"acquirer_nsu" form:"acquirer_nsu"` //TODO: Write general description for this field
    AcquirerAuthCode          string          `json:"acquirer_auth_code" form:"acquirer_auth_code"` //TODO: Write general description for this field
    OperationType             string          `json:"operation_type" form:"operation_type"` //TODO: Write general description for this field
    CreditCard                GetCreditCardResponse `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
    Installments              *int64          `json:"installments,omitempty" form:"installments,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetOrderResponse
 */
type GetOrderResponse struct {
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Code            string          `json:"code" form:"code"` //TODO: Write general description for this field
    Currency        string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Items           []*GetOrderItemResponse `json:"items" form:"items"` //TODO: Write general description for this field
    Customer        GetCustomerResponse `json:"customer" form:"customer"` //TODO: Write general description for this field
    Status          string          `json:"status" form:"status"` //TODO: Write general description for this field
    CreatedAt       *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt       *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    Charge          GetChargeResponse `json:"charge" form:"charge"` //TODO: Write general description for this field
    InvoiceUrl      string          `json:"invoice_url" form:"invoice_url"` //TODO: Write general description for this field
    Shipping        GetShippingResponse `json:"shipping" form:"shipping"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateAddressRequest
 */
type UpdateAddressRequest struct {
    Number          string          `json:"number" form:"number"` //TODO: Write general description for this field
    Complement      string          `json:"complement" form:"complement"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateCancelChargeRequest
 */
type CreateCancelChargeRequest struct {
    Amount          *int64          `json:"amount,omitempty" form:"amount,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateCaptureChargeRequest
 */
type CreateCaptureChargeRequest struct {
    Amount          *int64          `json:"amount,omitempty" form:"amount,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateChargeRequest
 */
type CreateChargeRequest struct {
    Code            string          `json:"code" form:"code"` //TODO: Write general description for this field
    Amount          int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    DueAt           *time.Time      `json:"due_at" form:"due_at"` //TODO: Write general description for this field
    CustomerId      string          `json:"customer_id" form:"customer_id"` //TODO: Write general description for this field
    Customer        CreateCustomerRequest `json:"customer" form:"customer"` //TODO: Write general description for this field
    Payment         CreatePaymentRequest `json:"payment" form:"payment"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateRescheduleSubscriptionRequest
 */
type CreateRescheduleSubscriptionRequest struct {
    NextBillingAt   *time.Time      `json:"next_billing_at" form:"next_billing_at"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetUsageResponse
 */
type GetUsageResponse struct {
    Id                string          `json:"id" form:"id"` //TODO: Write general description for this field
    Quantity          int64           `json:"quantity" form:"quantity"` //TODO: Write general description for this field
    Description       string          `json:"description" form:"description"` //TODO: Write general description for this field
    UsedAt            *time.Time      `json:"used_at" form:"used_at"` //TODO: Write general description for this field
    CreatedAt         *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    SubscriptionItem  GetSubscriptionItemResponse `json:"subscription_item" form:"subscription_item"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type ListOrderResponse
 */
type ListOrderResponse struct {
    Data            []*GetOrderResponse `json:"data" form:"data"` //TODO: Write general description for this field
    Paging          PagingResponse  `json:"paging" form:"paging"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type PagingResponse
 */
type PagingResponse struct {
    TotalItems      int64           `json:"total_items" form:"total_items"` //TODO: Write general description for this field
    CurrentPage     int64           `json:"current_page" form:"current_page"` //TODO: Write general description for this field
    TotalPages      int64           `json:"total_pages" form:"total_pages"` //TODO: Write general description for this field
    Previous        string          `json:"previous" form:"previous"` //TODO: Write general description for this field
    Next            string          `json:"next" form:"next"` //TODO: Write general description for this field
    First           string          `json:"first" form:"first"` //TODO: Write general description for this field
    Last            string          `json:"last" form:"last"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateCreditCardRequest
 */
type UpdateCreditCardRequest struct {
    HolderName         string          `json:"holder_name" form:"holder_name"` //TODO: Write general description for this field
    ExpMonth           int64           `json:"exp_month" form:"exp_month"` //TODO: Write general description for this field
    ExpYear            int64           `json:"exp_year" form:"exp_year"` //TODO: Write general description for this field
    BillingAddressId   string          `json:"billing_address_id" form:"billing_address_id"` //TODO: Write general description for this field
    BillingAddress     CreateAddressRequest `json:"billing_address" form:"billing_address"` //TODO: Write general description for this field
    Metadata           map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateCustomerRequest
 */
type UpdateCustomerRequest struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Phone           string          `json:"phone" form:"phone"` //TODO: Write general description for this field
    Email           string          `json:"email" form:"email"` //TODO: Write general description for this field
    Document        string          `json:"document" form:"document"` //TODO: Write general description for this field
    PersonType      string          `json:"person_type" form:"person_type"` //TODO: Write general description for this field
    Address         CreateAddressRequest `json:"address" form:"address"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdatePlanItemRequest
 */
type UpdatePlanItemRequest struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    Status          string          `json:"status" form:"status"` //TODO: Write general description for this field
    PricingScheme   UpdatePricingSchemeRequest `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    Quantity        *int64          `json:"quantity,omitempty" form:"quantity,omitempty"` //TODO: Write general description for this field
    Cycles          *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateSubscriptionItemRequest
 */
type UpdateSubscriptionItemRequest struct {
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    Status          string          `json:"status" form:"status"` //TODO: Write general description for this field
    PricingScheme   UpdatePricingSchemeRequest `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    Cycles          *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
    Quantity        *int64          `json:"quantity,omitempty" form:"quantity,omitempty"` //TODO: Write general description for this field
    MinimumPrice    *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateCancelSubscriptionRequest
 */
type CreateCancelSubscriptionRequest struct {
    CancelPendingInvoices   bool            `json:"cancel_pending_invoices" form:"cancel_pending_invoices"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateChargeDueDateRequest
 */
type UpdateChargeDueDateRequest struct {
    DueAt           *time.Time      `json:"due_at,omitempty" form:"due_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateUsageRequest
 */
type CreateUsageRequest struct {
    Quantity        int64           `json:"quantity" form:"quantity"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    UsedAt          *time.Time      `json:"used_at" form:"used_at"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateChargeCreditCardRequest
 */
type UpdateChargeCreditCardRequest struct {
    UpdateSubscription     bool            `json:"update_subscription" form:"update_subscription"` //TODO: Write general description for this field
    CreditCardId           string          `json:"credit_card_id" form:"credit_card_id"` //TODO: Write general description for this field
    CreditCardGatewayId    string          `json:"credit_card_gateway_id" form:"credit_card_gateway_id"` //TODO: Write general description for this field
    CreditCard             CreateCreditCardRequest `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateChargePaymentMethodRequest
 */
type UpdateChargePaymentMethodRequest struct {
    UpdateSubscription  bool            `json:"update_subscription" form:"update_subscription"` //TODO: Write general description for this field
    PaymentMethod       string          `json:"payment_method" form:"payment_method"` //TODO: Write general description for this field
    CreditCard          CreateCreditCardPaymentRequest `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
    Boleto              CreateBoletoPaymentRequest `json:"boleto" form:"boleto"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdatePricingSchemeRequest
 */
type UpdatePricingSchemeRequest struct {
    SchemeType      string          `json:"scheme_type" form:"scheme_type"` //TODO: Write general description for this field
    PriceBrackets   []*UpdatePriceBracketRequest `json:"price_brackets" form:"price_brackets"` //TODO: Write general description for this field
    Price           *int64          `json:"price,omitempty" form:"price,omitempty"` //TODO: Write general description for this field
    MinimumPrice    *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdatePriceBracketRequest
 */
type UpdatePriceBracketRequest struct {
    StartQuantity   int64           `json:"start_quantity" form:"start_quantity"` //TODO: Write general description for this field
    Price           int64           `json:"price" form:"price"` //TODO: Write general description for this field
    EndQuantity     *int64          `json:"end_quantity,omitempty" form:"end_quantity,omitempty"` //TODO: Write general description for this field
    OveragePrice    *int64          `json:"overage_price,omitempty" form:"overage_price,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateAddressRequest
 */
type CreateAddressRequest struct {
    Street          string          `json:"street" form:"street"` //TODO: Write general description for this field
    Number          string          `json:"number" form:"number"` //TODO: Write general description for this field
    ZipCode         string          `json:"zip_code" form:"zip_code"` //TODO: Write general description for this field
    Neighborhood    string          `json:"neighborhood" form:"neighborhood"` //TODO: Write general description for this field
    City            string          `json:"city" form:"city"` //TODO: Write general description for this field
    State           string          `json:"state" form:"state"` //TODO: Write general description for this field
    Country         string          `json:"country" form:"country"` //TODO: Write general description for this field
    Complement      string          `json:"complement" form:"complement"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateCreditCardRequest
 */
type CreateCreditCardRequest struct {
    Number             string          `json:"number" form:"number"` //TODO: Write general description for this field
    HolderName         string          `json:"holder_name" form:"holder_name"` //TODO: Write general description for this field
    ExpMonth           int64           `json:"exp_month" form:"exp_month"` //TODO: Write general description for this field
    ExpYear            int64           `json:"exp_year" form:"exp_year"` //TODO: Write general description for this field
    Cvv                string          `json:"cvv" form:"cvv"` //TODO: Write general description for this field
    BillingAddress     CreateAddressRequest `json:"billing_address" form:"billing_address"` //TODO: Write general description for this field
    Brand              string          `json:"brand" form:"brand"` //TODO: Write general description for this field
    Token              string          `json:"token" form:"token"` //TODO: Write general description for this field
    BillingAddressId   string          `json:"billing_address_id" form:"billing_address_id"` //TODO: Write general description for this field
    Metadata           map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateOrderItemRequest
 */
type CreateOrderItemRequest struct {
    Amount          int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    Quantity        int64           `json:"quantity" form:"quantity"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateCreditCardPaymentRequest
 */
type CreateCreditCardPaymentRequest struct {
    Installments             int64           `json:"installments" form:"installments"` //TODO: Write general description for this field
    StatementDescriptor      string          `json:"statement_descriptor" form:"statement_descriptor"` //Texto na fatura do cartão de crédito
    CreditCardInfo           CreateCreditCardRequest `json:"credit_card_info" form:"credit_card_info"` //TODO: Write general description for this field
    Retries                  int64           `json:"retries" form:"retries"` //TODO: Write general description for this field
    Capture                  bool            `json:"capture" form:"capture"` //TODO: Write general description for this field
    UpdateSubscriptionCard   bool            `json:"update_subscription_card" form:"update_subscription_card"` //Indica se o cartão da assinatura deve ser atualizado
    CreditCardId             string          `json:"credit_card_id" form:"credit_card_id"` //TODO: Write general description for this field
    CreditCardGatewayId      string          `json:"credit_card_gateway_id" form:"credit_card_gateway_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateCustomerRequest
 */
type CreateCustomerRequest struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Email           string          `json:"email" form:"email"` //TODO: Write general description for this field
    Phone           string          `json:"phone" form:"phone"` //TODO: Write general description for this field
    Document        string          `json:"document" form:"document"` //TODO: Write general description for this field
    PersonType      string          `json:"person_type" form:"person_type"` //TODO: Write general description for this field
    Address         CreateAddressRequest `json:"address" form:"address"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateDiscountRequest
 */
type CreateDiscountRequest struct {
    Value           int64           `json:"value" form:"value"` //TODO: Write general description for this field
    DiscountType    string          `json:"discount_type" form:"discount_type"` //TODO: Write general description for this field
    ItemId          string          `json:"item_id" form:"item_id"` //TODO: Write general description for this field
    Cycles          *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreatePlanItemRequest
 */
type CreatePlanItemRequest struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    PricingScheme   CreatePricingSchemeRequest `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    Cycles          *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
    Quantity        *int64          `json:"quantity,omitempty" form:"quantity,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreatePlanRequest
 */
type CreatePlanRequest struct {
    Name                 string          `json:"name" form:"name"` //TODO: Write general description for this field
    Description          string          `json:"description" form:"description"` //TODO: Write general description for this field
    StatementDescriptor  string          `json:"statement_descriptor" form:"statement_descriptor"` //TODO: Write general description for this field
    Items                []*CreatePlanItemRequest `json:"items" form:"items"` //TODO: Write general description for this field
    Shippable            bool            `json:"shippable" form:"shippable"` //TODO: Write general description for this field
    PaymentMethods       []string        `json:"payment_methods" form:"payment_methods"` //TODO: Write general description for this field
    Installments         []int64         `json:"installments" form:"installments"` //TODO: Write general description for this field
    Currency             string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Interval             string          `json:"interval" form:"interval"` //TODO: Write general description for this field
    IntervalCount        int64           `json:"interval_count" form:"interval_count"` //TODO: Write general description for this field
    BillingDays          []int64         `json:"billing_days" form:"billing_days"` //TODO: Write general description for this field
    BillingType          string          `json:"billing_type" form:"billing_type"` //TODO: Write general description for this field
    PricingScheme        CreatePricingSchemeRequest `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    Metadata             map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    MinimumPrice         *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
    Cycles               *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
    Quantity             *int64          `json:"quantity,omitempty" form:"quantity,omitempty"` //TODO: Write general description for this field
    TrialPeriodDays      *int64          `json:"trial_period_days,omitempty" form:"trial_period_days,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreatePricingSchemeRequest
 */
type CreatePricingSchemeRequest struct {
    SchemeType      string          `json:"scheme_type" form:"scheme_type"` //TODO: Write general description for this field
    PriceBrackets   []*CreatePriceBracketRequest `json:"price_brackets" form:"price_brackets"` //TODO: Write general description for this field
    Price           *int64          `json:"price,omitempty" form:"price,omitempty"` //TODO: Write general description for this field
    MinimumPrice    *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateSubscriptionItemRequest
 */
type CreateSubscriptionItemRequest struct {
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    PricingScheme   CreatePricingSchemeRequest `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    PlanItemId      string          `json:"plan_item_id" form:"plan_item_id"` //TODO: Write general description for this field
    Discounts       []*CreateDiscountRequest `json:"discounts" form:"discounts"` //TODO: Write general description for this field
    Cycles          *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
    Quantity        *int64          `json:"quantity,omitempty" form:"quantity,omitempty"` //TODO: Write general description for this field
    MinimumPrice    *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateShippingRequest
 */
type CreateShippingRequest struct {
    Amount          int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    RecipientName   string          `json:"recipient_name" form:"recipient_name"` //TODO: Write general description for this field
    RecipientPhone  string          `json:"recipient_phone" form:"recipient_phone"` //TODO: Write general description for this field
    AddressId       string          `json:"address_id" form:"address_id"` //TODO: Write general description for this field
    Address         CreateAddressRequest `json:"address" form:"address"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdatePlanRequest
 */
type UpdatePlanRequest struct {
    Name                 string          `json:"name" form:"name"` //TODO: Write general description for this field
    Description          string          `json:"description" form:"description"` //TODO: Write general description for this field
    Installments         []int64         `json:"installments" form:"installments"` //TODO: Write general description for this field
    StatementDescriptor  string          `json:"statement_descriptor" form:"statement_descriptor"` //TODO: Write general description for this field
    Currency             string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Interval             string          `json:"interval" form:"interval"` //TODO: Write general description for this field
    IntervalCount        int64           `json:"interval_count" form:"interval_count"` //TODO: Write general description for this field
    PaymentMethods       []string        `json:"payment_methods" form:"payment_methods"` //TODO: Write general description for this field
    BillingType          string          `json:"billing_type" form:"billing_type"` //TODO: Write general description for this field
    Status               string          `json:"status" form:"status"` //TODO: Write general description for this field
    Shippable            bool            `json:"shippable" form:"shippable"` //TODO: Write general description for this field
    BillingDays          []int64         `json:"billing_days" form:"billing_days"` //TODO: Write general description for this field
    Metadata             map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    MinimumPrice         *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
    TrialPeriodDays      *int64          `json:"trial_period_days,omitempty" form:"trial_period_days,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateSubscriptionCreditCardRequest
 */
type UpdateSubscriptionCreditCardRequest struct {
    CreditCard             CreateCreditCardRequest `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
    CreditCardId           string          `json:"credit_card_id" form:"credit_card_id"` //TODO: Write general description for this field
    CreditCardGatewayId    string          `json:"credit_card_gateway_id" form:"credit_card_gateway_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type UpdateSubscriptionPaymentMethodRequest
 */
type UpdateSubscriptionPaymentMethodRequest struct {
    PaymentMethod          string          `json:"payment_method" form:"payment_method"` //TODO: Write general description for this field
    CreditCardId           string          `json:"credit_card_id" form:"credit_card_id"` //TODO: Write general description for this field
    CreditCardGatewayId    string          `json:"credit_card_gateway_id" form:"credit_card_gateway_id"` //TODO: Write general description for this field
    CreditCard             CreateCreditCardRequest `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetOrderItemResponse
 */
type GetOrderItemResponse struct {
    Amount          int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    Quantity        int64           `json:"quantity" form:"quantity"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetTransactionResponse
 */
type GetTransactionResponse struct {
    TransactionType           string          `json:"transaction_type" form:"transaction_type"` //TODO: Write general description for this field
    GatewayId                 string          `json:"gateway_id" form:"gateway_id"` //TODO: Write general description for this field
    Amount                    int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    Status                    string          `json:"status" form:"status"` //TODO: Write general description for this field
    Success                   bool            `json:"success" form:"success"` //TODO: Write general description for this field
    Installments              int64           `json:"installments" form:"installments"` //TODO: Write general description for this field
    StatementDescriptor       string          `json:"statement_descriptor" form:"statement_descriptor"` //TODO: Write general description for this field
    AcquirerName              string          `json:"acquirer_name" form:"acquirer_name"` //TODO: Write general description for this field
    AcquirerAffiliationCode   string          `json:"acquirer_affiliation_code" form:"acquirer_affiliation_code"` //TODO: Write general description for this field
    AcquirerTid               string          `json:"acquirer_tid" form:"acquirer_tid"` //TODO: Write general description for this field
    AcquirerNsu               string          `json:"acquirer_nsu" form:"acquirer_nsu"` //TODO: Write general description for this field
    AcquirerAuthCode          string          `json:"acquirer_auth_code" form:"acquirer_auth_code"` //TODO: Write general description for this field
    OperationType             string          `json:"operation_type" form:"operation_type"` //TODO: Write general description for this field
    CreditCard                GetCreditCardResponse `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
    CreatedAt                 *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt                 *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    AttemptCount              int64           `json:"attempt_count" form:"attempt_count"` //TODO: Write general description for this field
    MaxAttempts               int64           `json:"max_attempts" form:"max_attempts"` //TODO: Write general description for this field
    NextAttempt               *time.Time      `json:"next_attempt,omitempty" form:"next_attempt,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetBillingAddressResponse
 */
type GetBillingAddressResponse struct {
    Street          string          `json:"street" form:"street"` //TODO: Write general description for this field
    Number          string          `json:"number" form:"number"` //TODO: Write general description for this field
    ZipCode         string          `json:"zip_code" form:"zip_code"` //TODO: Write general description for this field
    Neighborhood    string          `json:"neighborhood" form:"neighborhood"` //TODO: Write general description for this field
    City            string          `json:"city" form:"city"` //TODO: Write general description for this field
    State           string          `json:"state" form:"state"` //TODO: Write general description for this field
    Country         string          `json:"country" form:"country"` //TODO: Write general description for this field
    Complement      string          `json:"complement" form:"complement"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetInvoiceResponse
 */
type GetInvoiceResponse struct {
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Code            string          `json:"code" form:"code"` //TODO: Write general description for this field
    Url             string          `json:"url" form:"url"` //TODO: Write general description for this field
    Amount          int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    Status          string          `json:"status" form:"status"` //TODO: Write general description for this field
    PaymentMethod   string          `json:"payment_method" form:"payment_method"` //TODO: Write general description for this field
    CreatedAt       *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    Items           []*GetInvoiceItemResponse `json:"items" form:"items"` //TODO: Write general description for this field
    Customer        GetCustomerResponse `json:"customer" form:"customer"` //TODO: Write general description for this field
    Charge          GetChargeResponse `json:"charge" form:"charge"` //TODO: Write general description for this field
    Installments    int64           `json:"installments" form:"installments"` //TODO: Write general description for this field
    BillingAddress  GetBillingAddressResponse `json:"billing_address" form:"billing_address"` //TODO: Write general description for this field
    Subscription    GetSubscriptionResponse `json:"subscription" form:"subscription"` //TODO: Write general description for this field
    Cycle           GetPeriodResponse `json:"cycle" form:"cycle"` //TODO: Write general description for this field
    Shipping        GetShippingResponse `json:"shipping" form:"shipping"` //TODO: Write general description for this field
    DueAt           *time.Time      `json:"due_at,omitempty" form:"due_at,omitempty"` //TODO: Write general description for this field
    CanceledAt      *time.Time      `json:"canceled_at,omitempty" form:"canceled_at,omitempty"` //TODO: Write general description for this field
    BillingAt       *time.Time      `json:"billing_at,omitempty" form:"billing_at,omitempty"` //TODO: Write general description for this field
    SeenAt          *time.Time      `json:"seen_at,omitempty" form:"seen_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetCreditCardResponse
 */
type GetCreditCardResponse struct {
    Id               string          `json:"id" form:"id"` //TODO: Write general description for this field
    GatewayId        string          `json:"gateway_id" form:"gateway_id"` //TODO: Write general description for this field
    LastFourDigits   string          `json:"last_four_digits" form:"last_four_digits"` //TODO: Write general description for this field
    Brand            string          `json:"brand" form:"brand"` //TODO: Write general description for this field
    HolderName       string          `json:"holder_name" form:"holder_name"` //TODO: Write general description for this field
    ExpMonth         int64           `json:"exp_month" form:"exp_month"` //TODO: Write general description for this field
    ExpYear          int64           `json:"exp_year" form:"exp_year"` //TODO: Write general description for this field
    Status           string          `json:"status" form:"status"` //TODO: Write general description for this field
    CreatedAt        *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt        *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    BillingAddress   GetBillingAddressResponse `json:"billing_address" form:"billing_address"` //TODO: Write general description for this field
    Customer         GetCustomerResponse `json:"customer" form:"customer"` //TODO: Write general description for this field
    Metadata         map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    DeletedAt        *time.Time      `json:"deleted_at,omitempty" form:"deleted_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetAddressResponse
 */
type GetAddressResponse struct {
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Street          string          `json:"street" form:"street"` //TODO: Write general description for this field
    Number          string          `json:"number" form:"number"` //TODO: Write general description for this field
    Complement      string          `json:"complement" form:"complement"` //TODO: Write general description for this field
    ZipCode         string          `json:"zip_code" form:"zip_code"` //TODO: Write general description for this field
    Neighborhood    string          `json:"neighborhood" form:"neighborhood"` //TODO: Write general description for this field
    City            string          `json:"city" form:"city"` //TODO: Write general description for this field
    State           string          `json:"state" form:"state"` //TODO: Write general description for this field
    Country         string          `json:"country" form:"country"` //TODO: Write general description for this field
    Status          string          `json:"status" form:"status"` //TODO: Write general description for this field
    CreatedAt       *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt       *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    Customer        GetCustomerResponse `json:"customer" form:"customer"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    DeletedAt       *time.Time      `json:"deleted_at,omitempty" form:"deleted_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetChargeResponse
 */
type GetChargeResponse struct {
    Id               string          `json:"id" form:"id"` //TODO: Write general description for this field
    Code             string          `json:"code" form:"code"` //TODO: Write general description for this field
    GatewayId        string          `json:"gateway_id" form:"gateway_id"` //TODO: Write general description for this field
    Amount           int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    Status           string          `json:"status" form:"status"` //TODO: Write general description for this field
    Currency         string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    PaymentMethod    string          `json:"payment_method" form:"payment_method"` //TODO: Write general description for this field
    DueAt            *time.Time      `json:"due_at" form:"due_at"` //TODO: Write general description for this field
    CreatedAt        *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt        *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    LastTransaction  GetTransactionResponse `json:"last_transaction" form:"last_transaction"` //TODO: Write general description for this field
    Invoice          GetInvoiceResponse `json:"invoice" form:"invoice"` //TODO: Write general description for this field
    Order            GetOrderResponse `json:"order" form:"order"` //TODO: Write general description for this field
    Customer         GetCustomerResponse `json:"customer" form:"customer"` //TODO: Write general description for this field
    Metadata         map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    PaidAt           *time.Time      `json:"paid_at,omitempty" form:"paid_at,omitempty"` //TODO: Write general description for this field
    CanceledAt       *time.Time      `json:"canceled_at,omitempty" form:"canceled_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetInvoiceItemResponse
 */
type GetInvoiceItemResponse struct {
    Amount          int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    PricingScheme   GetPricingSchemeResponse `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    PriceBracket    GetPriceBracketResponse `json:"price_bracket" form:"price_bracket"` //TODO: Write general description for this field
    Quantity        *int64          `json:"quantity,omitempty" form:"quantity,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetSubscriptionResponse
 */
type GetSubscriptionResponse struct {
    Id                   string          `json:"id" form:"id"` //TODO: Write general description for this field
    Code                 string          `json:"code" form:"code"` //TODO: Write general description for this field
    StartAt              *time.Time      `json:"start_at" form:"start_at"` //TODO: Write general description for this field
    Interval             string          `json:"interval" form:"interval"` //TODO: Write general description for this field
    IntervalCount        int64           `json:"interval_count" form:"interval_count"` //TODO: Write general description for this field
    BillingType          string          `json:"billing_type" form:"billing_type"` //TODO: Write general description for this field
    CurrentPeriod        GetPeriodResponse `json:"current_period" form:"current_period"` //TODO: Write general description for this field
    PaymentMethod        string          `json:"payment_method" form:"payment_method"` //TODO: Write general description for this field
    Currency             string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Installments         int64           `json:"installments" form:"installments"` //TODO: Write general description for this field
    Status               string          `json:"status" form:"status"` //TODO: Write general description for this field
    CreatedAt            *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt            *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    Customer             GetCustomerResponse `json:"customer" form:"customer"` //TODO: Write general description for this field
    CreditCard           GetCreditCardResponse `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
    Items                []*GetSubscriptionItemResponse `json:"items" form:"items"` //TODO: Write general description for this field
    StatementDescriptor  string          `json:"statement_descriptor" form:"statement_descriptor"` //TODO: Write general description for this field
    Metadata             map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    NextBillingAt        *time.Time      `json:"next_billing_at,omitempty" form:"next_billing_at,omitempty"` //TODO: Write general description for this field
    BillingDay           *int64          `json:"billing_day,omitempty" form:"billing_day,omitempty"` //TODO: Write general description for this field
    MinimumPrice         *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
    CanceledAt           *time.Time      `json:"canceled_at,omitempty" form:"canceled_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetSubscriptionItemResponse
 */
type GetSubscriptionItemResponse struct {
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    Status          string          `json:"status" form:"status"` //TODO: Write general description for this field
    CreatedAt       *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt       *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    PricingScheme   GetPricingSchemeResponse `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    Discounts       []*GetDiscountResponse `json:"discounts" form:"discounts"` //TODO: Write general description for this field
    Subscription    GetSubscriptionResponse `json:"subscription" form:"subscription"` //TODO: Write general description for this field
    Quantity        *int64          `json:"quantity,omitempty" form:"quantity,omitempty"` //TODO: Write general description for this field
    Cycles          *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
    DeletedAt       *time.Time      `json:"deleted_at,omitempty" form:"deleted_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetPricingSchemeResponse
 */
type GetPricingSchemeResponse struct {
    Price           int64           `json:"price" form:"price"` //TODO: Write general description for this field
    SchemeType      string          `json:"scheme_type" form:"scheme_type"` //TODO: Write general description for this field
    PriceBrackets   []*GetPriceBracketResponse `json:"price_brackets" form:"price_brackets"` //TODO: Write general description for this field
    MinimumPrice    *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetDiscountResponse
 */
type GetDiscountResponse struct {
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Value           float64         `json:"value" form:"value"` //TODO: Write general description for this field
    DiscountType    string          `json:"discount_type" form:"discount_type"` //TODO: Write general description for this field
    Status          string          `json:"status" form:"status"` //TODO: Write general description for this field
    CreatedAt       *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    Subscription    GetSubscriptionResponse `json:"subscription" form:"subscription"` //TODO: Write general description for this field
    Cycles          *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
    DeletedAt       *time.Time      `json:"deleted_at,omitempty" form:"deleted_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetPlanResponse
 */
type GetPlanResponse struct {
    Id                   string          `json:"id" form:"id"` //TODO: Write general description for this field
    Name                 string          `json:"name" form:"name"` //TODO: Write general description for this field
    Description          string          `json:"description" form:"description"` //TODO: Write general description for this field
    Url                  string          `json:"url" form:"url"` //TODO: Write general description for this field
    StatementDescriptor  string          `json:"statement_descriptor" form:"statement_descriptor"` //TODO: Write general description for this field
    Interval             string          `json:"interval" form:"interval"` //TODO: Write general description for this field
    IntervalCount        int64           `json:"interval_count" form:"interval_count"` //TODO: Write general description for this field
    BillingType          string          `json:"billing_type" form:"billing_type"` //TODO: Write general description for this field
    PaymentMethods       []string        `json:"payment_methods" form:"payment_methods"` //TODO: Write general description for this field
    Installments         []int64         `json:"installments" form:"installments"` //TODO: Write general description for this field
    Status               string          `json:"status" form:"status"` //TODO: Write general description for this field
    Currency             string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    CreatedAt            *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt            *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    Items                []*GetPlanItemResponse `json:"items" form:"items"` //TODO: Write general description for this field
    BillingDays          []int64         `json:"billing_days" form:"billing_days"` //TODO: Write general description for this field
    Shippable            bool            `json:"shippable" form:"shippable"` //TODO: Write general description for this field
    Metadata             map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    TrialPeriodDays      *int64          `json:"trial_period_days,omitempty" form:"trial_period_days,omitempty"` //TODO: Write general description for this field
    MinimumPrice         *int64          `json:"minimum_price,omitempty" form:"minimum_price,omitempty"` //TODO: Write general description for this field
    DeletedAt            *time.Time      `json:"deleted_at,omitempty" form:"deleted_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetPlanItemResponse
 */
type GetPlanItemResponse struct {
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Status          string          `json:"status" form:"status"` //TODO: Write general description for this field
    CreatedAt       *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt       *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    PricingScheme   GetPricingSchemeResponse `json:"pricing_scheme" form:"pricing_scheme"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    Plan            GetPlanResponse `json:"plan" form:"plan"` //TODO: Write general description for this field
    Quantity        *int64          `json:"quantity,omitempty" form:"quantity,omitempty"` //TODO: Write general description for this field
    Cycles          *int64          `json:"cycles,omitempty" form:"cycles,omitempty"` //TODO: Write general description for this field
    DeletedAt       *time.Time      `json:"deleted_at,omitempty" form:"deleted_at,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateBoletoPaymentRequest
 */
type CreateBoletoPaymentRequest struct {
    Retries         int64           `json:"retries" form:"retries"` //TODO: Write general description for this field
    Bank            string          `json:"bank" form:"bank"` //TODO: Write general description for this field
    Instructions    string          `json:"instructions" form:"instructions"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreatePaymentRequest
 */
type CreatePaymentRequest struct {
    PaymentMethod   string          `json:"payment_method" form:"payment_method"` //TODO: Write general description for this field
    CreditCard      CreateCreditCardPaymentRequest `json:"credit_card" form:"credit_card"` //TODO: Write general description for this field
    Boleto          CreateBoletoPaymentRequest `json:"boleto" form:"boleto"` //TODO: Write general description for this field
    Currency        string          `json:"currency" form:"currency"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateOrderRequest
 */
type CreateOrderRequest struct {
    Items           []*CreateOrderItemRequest `json:"items" form:"items"` //TODO: Write general description for this field
    Customer        CreateCustomerRequest `json:"customer" form:"customer"` //TODO: Write general description for this field
    Payment         CreatePaymentRequest `json:"payment" form:"payment"` //TODO: Write general description for this field
    Code            string          `json:"code" form:"code"` //TODO: Write general description for this field
    CustomerId      string          `json:"customer_id" form:"customer_id"` //TODO: Write general description for this field
    Shipping        CreateShippingRequest `json:"shipping" form:"shipping"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreatePriceBracketRequest
 */
type CreatePriceBracketRequest struct {
    StartQuantity   int64           `json:"start_quantity" form:"start_quantity"` //TODO: Write general description for this field
    Price           int64           `json:"price" form:"price"` //TODO: Write general description for this field
    EndQuantity     *int64          `json:"end_quantity,omitempty" form:"end_quantity,omitempty"` //TODO: Write general description for this field
    OveragePrice    *int64          `json:"overage_price,omitempty" form:"overage_price,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetPeriodResponse
 */
type GetPeriodResponse struct {
    StartAt         *time.Time      `json:"start_at" form:"start_at"` //TODO: Write general description for this field
    EndAt           *time.Time      `json:"end_at" form:"end_at"` //TODO: Write general description for this field
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    BillingAt       *time.Time      `json:"billing_at" form:"billing_at"` //TODO: Write general description for this field
    Subscription    GetSubscriptionResponse `json:"subscription" form:"subscription"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetPriceBracketResponse
 */
type GetPriceBracketResponse struct {
    StartQuantity   int64           `json:"start_quantity" form:"start_quantity"` //TODO: Write general description for this field
    Price           int64           `json:"price" form:"price"` //TODO: Write general description for this field
    EndQuantity     *int64          `json:"end_quantity,omitempty" form:"end_quantity,omitempty"` //TODO: Write general description for this field
    OveragePrice    *int64          `json:"overage_price,omitempty" form:"overage_price,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetShippingResponse
 */
type GetShippingResponse struct {
    Amount          int64           `json:"amount" form:"amount"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    RecipientName   string          `json:"recipient_name" form:"recipient_name"` //TODO: Write general description for this field
    RecipientPhone  string          `json:"recipient_phone" form:"recipient_phone"` //TODO: Write general description for this field
    Address         GetAddressResponse `json:"address" form:"address"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetCustomerResponse
 */
type GetCustomerResponse struct {
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Email           string          `json:"email" form:"email"` //TODO: Write general description for this field
    Delinquent      bool            `json:"delinquent" form:"delinquent"` //TODO: Write general description for this field
    CreatedAt       *time.Time      `json:"created_at" form:"created_at"` //TODO: Write general description for this field
    UpdatedAt       *time.Time      `json:"updated_at" form:"updated_at"` //TODO: Write general description for this field
    Phone           string          `json:"phone" form:"phone"` //TODO: Write general description for this field
    Document        string          `json:"document" form:"document"` //TODO: Write general description for this field
    PersonType      string          `json:"person_type" form:"person_type"` //TODO: Write general description for this field
    FbAccessToken   string          `json:"fb_access_token" form:"fb_access_token"` //TODO: Write general description for this field
    Address         GetAddressResponse `json:"address" form:"address"` //TODO: Write general description for this field
    Metadata        map[string]string `json:"metadata" form:"metadata"` //TODO: Write general description for this field
    FbId            *int64          `json:"fb_id,omitempty" form:"fb_id,omitempty"` //TODO: Write general description for this field
}
