/*
 * mundicoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/02/2017
 */

package customers_pkg

import "mundicoreapi_lib/models_pkg"

/*
 * Interface for the CUSTOMERS_IMPL
 */
type CUSTOMERS interface {
    UpdateCreditCard (string, string, *models_pkg.UpdateCreditCardRequest) (*models_pkg.GetCreditCardResponse, error)

    UpdateAddress (string, string, *models_pkg.UpdateAddressRequest) (*models_pkg.GetAddressResponse, error)

    GetCustomerOrders (string) (interface{}, error)

    GetCustomer (string) (*models_pkg.GetCustomerResponse, error)

    CreateCustomer (*models_pkg.CreateCustomerRequest) (*models_pkg.GetCustomerResponse, error)

    UpdateCustomer (string, *models_pkg.UpdateCustomerRequest) (error)

    ListCustomers () (interface{}, error)

    GetCustomerOrders1 (string) (interface{}, error)

    CreateCreditCard (*models_pkg.CreateCreditCardRequest, string) (*models_pkg.GetCreditCardResponse, error)

    ListCreditCards (string) (interface{}, error)

    GetCreditCard (string, string) (*models_pkg.GetCreditCardResponse, error)

    CreateAddress (string, *models_pkg.CreateAddressRequest) (*models_pkg.GetAddressResponse, error)

    DeleteCreditCard (string, string) (*models_pkg.GetCreditCardResponse, error)

    DeleteAddress (string, string) (*models_pkg.GetAddressResponse, error)

    GetCustomerOrders2 (string) (interface{}, error)

    ListAddresses (string) (interface{}, error)

    GetAddress (string, string) (*models_pkg.GetAddressResponse, error)

    GetCustomerInvoices (string) (interface{}, error)

    GetCustomerSubscriptions (string) (interface{}, error)

    GetCustomerCharges (string) (interface{}, error)
}

/*
 * Factory for the CUSTOMERS interaface returning CUSTOMERS_IMPL
 */
func NewCUSTOMERS() CUSTOMERS {
    return &CUSTOMERS_IMPL{}
}