/*
 * mundicoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/02/2017
 */

package mundicoreapi_lib

/** The base Uri for API calls */
const BASEURI string = "https://api.mundipagg.com/core/v1.0"

var Config struct {
    /** The username to use with basic authentication */
    /** Replace the value of BasicAuthUserName with an appropriate value */
    BasicAuthUserName string
    /** The password to use with basic authentication */
    /** Replace the value of BasicAuthPassword with an appropriate value */
    BasicAuthPassword string
}
