/*
 * mundicoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/02/2017
 */

package invoices_pkg

import "mundicoreapi_lib/models_pkg"

/*
 * Interface for the INVOICES_IMPL
 */
type INVOICES interface {
    GetInvoice (string) (*models_pkg.GetInvoiceResponse, error)

    ListInvoices () (interface{}, error)

    GetLastInvoiceCharge (string) (*models_pkg.GetChargeResponse, error)

    DeleteCancelInvoice (string) (*models_pkg.GetInvoiceResponse, error)
}

/*
 * Factory for the INVOICES interaface returning INVOICES_IMPL
 */
func NewINVOICES() INVOICES {
    return &INVOICES_IMPL{}
}