/*
 * mundicoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/02/2017
 */

package charges_pkg

import "mundicoreapi_lib/models_pkg"

/*
 * Interface for the CHARGES_IMPL
 */
type CHARGES interface {
    UpdateChargePaymentMethod (*models_pkg.UpdateChargePaymentMethodRequest, string) (*models_pkg.GetChargeResponse, error)

    CreateCaptureCharge (string, *models_pkg.CreateCaptureChargeRequest) (*models_pkg.GetChargeResponse, error)

    CreateCharge (*models_pkg.CreateChargeRequest) (*models_pkg.GetChargeResponse, error)

    ListCharges () (interface{}, error)

    DeleteCancelCharge (*models_pkg.CreateCancelChargeRequest, string) (*models_pkg.GetChargeResponse, error)

    UpdateChargeCreditCard (*models_pkg.UpdateChargeCreditCardRequest, string) (*models_pkg.GetChargeResponse, error)

    UpdateChargeDueDate (string, *models_pkg.UpdateChargeDueDateRequest) (*models_pkg.GetChargeResponse, error)

    CreateRetryCharge (string) (*models_pkg.GetChargeResponse, error)

    UpdateChargeCreditCard1 (*models_pkg.UpdateChargeCreditCardRequest, string) (*models_pkg.GetChargeResponse, error)

    GetChargeTransactions (string) (interface{}, error)

    GetCharge (string) (*models_pkg.GetChargeResponse, error)
}

/*
 * Factory for the CHARGES interaface returning CHARGES_IMPL
 */
func NewCHARGES() CHARGES {
    return &CHARGES_IMPL{}
}