/*
 * mundicoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/02/2017
 */

package subscriptions_pkg

import "mundicoreapi_lib/models_pkg"

/*
 * Interface for the SUBSCRIPTIONS_IMPL
 */
type SUBSCRIPTIONS interface {
    UpdateSubscriptionPaymentMethod (*models_pkg.UpdateSubscriptionPaymentMethodRequest, string) (*models_pkg.GetSubscriptionResponse, error)

    CreateDiscount (*models_pkg.CreateDiscountRequest, string) (*models_pkg.GetDiscountResponse, error)

    DeleteSubscriptionItem (string, string) (*models_pkg.GetSubscriptionItemResponse, error)

    UpdateSubscriptionCreditCard (*models_pkg.UpdateSubscriptionCreditCardRequest, string) (*models_pkg.GetSubscriptionResponse, error)

    UpdateRescheduleSubscription (string, *models_pkg.CreateRescheduleSubscriptionRequest) (*models_pkg.GetSubscriptionResponse, error)

    UpdateSubscriptionItem (string, string, *models_pkg.UpdateSubscriptionItemRequest) (*models_pkg.GetSubscriptionItemResponse, error)

    CreateUsage (string, string, *models_pkg.CreateUsageRequest) (*models_pkg.GetUsageResponse, error)

    GetUsage (string, string, string) (*models_pkg.GetUsageResponse, error)

    GetSubscription (string) (*models_pkg.GetSubscriptionResponse, error)

    DeleteCancelSubscription (string, *models_pkg.CreateCancelSubscriptionRequest) (*models_pkg.GetSubscriptionResponse, error)

    ListSubscriptions () (interface{}, error)

    DeleteDiscount (string, string) (*models_pkg.GetDiscountResponse, error)

    CreateDiscount1 (*models_pkg.CreateDiscountRequest, string) (*models_pkg.GetDiscountResponse, error)

    GetSubscriptionItem (string, string) (*models_pkg.GetSubscriptionItemResponse, error)

    GetDeleteDiscount (string, string) (*models_pkg.GetDiscountResponse, error)

    GetDiscount (string, string) (*models_pkg.GetDiscountResponse, error)

    GetCycle (string, string) (*models_pkg.GetPeriodResponse, error)

    GetSubscriptionCycles (string) (interface{}, error)

    GetSubscriptionInvoices (string) (interface{}, error)

    CreateInvoice (string, string) (*models_pkg.GetInvoiceResponse, error)

    GetLastSubscriptionCharge (string) (*models_pkg.GetChargeResponse, error)

    GetLastSubscriptionCharge1 (string) (*models_pkg.GetChargeResponse, error)

    GetLastSubscriptionCharge2 (string) (*models_pkg.GetChargeResponse, error)

    CreateSubscription (*models_pkg.CreateSubscriptionRequest) (*models_pkg.GetSubscriptionResponse, error)

    CreateSubscriptionItem (*models_pkg.CreateSubscriptionItemRequest, string) (*models_pkg.GetSubscriptionItemResponse, error)
}

/*
 * Factory for the SUBSCRIPTIONS interaface returning SUBSCRIPTIONS_IMPL
 */
func NewSUBSCRIPTIONS() SUBSCRIPTIONS {
    return &SUBSCRIPTIONS_IMPL{}
}