/*
 * mundicoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/02/2017
 */

package orders_pkg

import "mundicoreapi_lib/models_pkg"

/*
 * Interface for the ORDERS_IMPL
 */
type ORDERS interface {
    CreateOrder (*models_pkg.CreateOrderRequest) (*models_pkg.GetOrderResponse, error)

    ListOrders () (interface{}, error)

    GetOrder (string) (*models_pkg.GetOrderResponse, error)
}

/*
 * Factory for the ORDERS interaface returning ORDERS_IMPL
 */
func NewORDERS() ORDERS {
    return &ORDERS_IMPL{}
}