/*
 * mundicoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/02/2017
 */

package plans_pkg

import "mundicoreapi_lib/models_pkg"

/*
 * Interface for the PLANS_IMPL
 */
type PLANS interface {
    CreatePlanItem (*models_pkg.CreatePlanItemRequest, string) (*models_pkg.GetPlanItemResponse, error)

    UpdatePlanItem (string, string, *models_pkg.UpdatePlanItemRequest) (*models_pkg.GetPlanItemResponse, error)

    DeletePlan (string) (*models_pkg.GetPlanResponse, error)

    ListPlans () (interface{}, error)

    DeletePlanItem (string, string) (*models_pkg.GetPlanItemResponse, error)

    GetPlan (string) (*models_pkg.GetPlanResponse, error)

    GetPlanItem (string, string) (*models_pkg.GetPlanItemResponse, error)

    GetPlanSubscriptions (string) (interface{}, error)

    GetPlanItems (string) (interface{}, error)

    UpdatePlan (*models_pkg.UpdatePlanRequest, string) (*models_pkg.GetPlanResponse, error)

    CreatePlan (*models_pkg.CreatePlanRequest) (*models_pkg.GetPlanResponse, error)
}

/*
 * Factory for the PLANS interaface returning PLANS_IMPL
 */
func NewPLANS() PLANS {
    return &PLANS_IMPL{}
}